version: '2'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/app:rw
